# Generated by Django 5.1.4 on 2025-01-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transferintent",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="transferintent",
            name="updated_at",
        ),
    ]
