# Generated by Django 5.1.4 on 2025-01-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_remove_transferintent_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledger",
            name="code",
            field=models.CharField(
                help_text="Code of the ledger", max_length=3, unique=True
            ),
            preserve_default=False,
        ),
    ]
