# Generated by Django 5.1.4 on 2025-01-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_ledger_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Charges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "currency",
                    models.CharField(
                        help_text="Currency code (e.g., USD, EUR)", max_length=3
                    ),
                ),
                ("charge", models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
